-- ============================================================
-- Migration 035: give a staff row the auth account it belongs to
-- ============================================================
-- `app_create_business_for_user` took `p_user_id uuid` and the dashboard passed
-- it the AUTH provider's account id. That typechecked only by coincidence:
-- Supabase Auth issues uuids, so `users.id` and the auth account id were the
-- same string and nobody had to decide whether they were the same THING.
--
-- Identity Platform issues a 28-character alphanumeric id. Measured, not
-- assumed:
--
--   SELECT app_create_business_for_user('7Ziacgk6NkY3lKC6dXu3VthNO1Y2', ...)
--   ERROR:  invalid input syntax for type uuid: "7Ziacgk6NkY3lKC6dXu3VthNO1Y2"
--
-- So B3 breaks signup — a 500 on POST /api/onboarding/create-business — and it
-- breaks it in the one place that has no test running the real middleware. This
-- is the "half-migrated auth path" failure: login works, and the first thing a
-- new customer does fails.
--
-- ------------------------------------------------------------------
-- Why a COLUMN and not a cast
-- ------------------------------------------------------------------
--
-- Deriving a uuid from the Identity Platform id — a v5 hash, say — would make
-- the type error go away and would throw the auth identity away in the process,
-- leaving `users.id` looking like an auth id while being a hash of one. The two
-- are genuinely different things and the coincidence that hid that is gone.
--
-- `users.id` goes back to being what it always was on paper: this system's own
-- identifier for a member of staff, generated by the DEFAULT, written into the
-- PHI audit trail, stable across a change of auth provider. `auth_uid` is the
-- account at the identity provider. NULLABLE, because every row that exists
-- today predates Identity Platform and has no account there yet — that backfill
-- is B1(2), the user import, and it cannot be guessed here.
--
-- ------------------------------------------------------------------
-- The duplicate guard, and why it is a UNIQUE INDEX again
-- ------------------------------------------------------------------
--
-- Migration 032 already learned this the hard way: the obvious guard is
--
--   SELECT 1 FROM users WHERE auth_uid = p_auth_uid
--
-- and under FORCE row-level security with no tenant set, that SELECT returns NO
-- ROWS for a user who definitely exists. The guard silently stops firing in
-- exactly the case it was written for. `ON CONFLICT` detects the collision on
-- the index, which is not subject to row visibility, so it works with or
-- without a scope. Same technique, one column along.
--
-- ------------------------------------------------------------------
-- What this SETS UP and does not yet do
-- ------------------------------------------------------------------
--
-- Migration 034 resolves a session's tenant BY EMAIL. That is safe only while
-- every address in `users` also has an Identity Platform account: signup is
-- open, so an address with a `users` row and NO auth account can be claimed by
-- a stranger, who then inherits that clinic's tenant. Nothing here changes that
-- — it becomes live at the moment of the B1(2) import, not before.
--
-- `auth_uid` is what closes it. Import every existing user with a known
-- account, backfill this column, make it NOT NULL, and move the lookup from
-- email to auth_uid — which a stranger's newly created account cannot collide
-- with. Recorded here rather than left as an intention, because the window
-- opens during an import that will look like it succeeded.
-- ============================================================

ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_uid text;

COMMENT ON COLUMN users.auth_uid IS
  'The identity provider''s account id (Identity Platform localId). NOT users.id, which is this system''s own staff identifier and what the PHI audit trail records. Nullable until the B1(2) import backfills existing rows; see migration 035.';

-- Nullable + UNIQUE: Postgres allows many NULLs in a unique index, which is
-- what lets pre-Identity-Platform rows coexist with new ones.
CREATE UNIQUE INDEX IF NOT EXISTS users_auth_uid_key ON users (auth_uid);

-- ------------------------------------------------------------------
-- The bootstrap, retyped.
--
-- A different argument type is a different function, so this is DROP + CREATE
-- rather than CREATE OR REPLACE, and the EXECUTE grant has to be re-made
-- because it belonged to the old signature.
--
-- Everything else is migration 032's body unchanged, including the reason it
-- looks like this: generate the id first, adopt it as the transaction-local
-- tenant, and the INSERT then satisfies `WITH CHECK (id = app_current_business_id())`
-- on its own terms instead of needing a bypass that Cloud SQL cannot grant.
-- ------------------------------------------------------------------
DROP FUNCTION IF EXISTS app_create_business_for_user(uuid, text, text, text);

CREATE OR REPLACE FUNCTION app_create_business_for_user(
  p_auth_uid text,
  p_email    text,
  p_name     text,
  p_timezone text
)
RETURNS businesses
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id       uuid := gen_random_uuid();
  v_previous text := current_setting('app.business_id', true);
  v_business businesses;
BEGIN
  IF p_auth_uid IS NULL OR btrim(p_auth_uid) = ''
     OR p_email IS NULL OR p_name IS NULL OR p_timezone IS NULL THEN
    RAISE EXCEPTION 'app_create_business_for_user: all arguments are required';
  END IF;

  -- Become the tenant being created, for the length of this transaction only.
  PERFORM set_config('app.business_id', v_id::text, true);

  -- Explicit id, because the policy compares against it. Letting the DEFAULT
  -- generate one is exactly what made 031 unsatisfiable.
  INSERT INTO businesses (id, name, timezone)
  VALUES (v_id, p_name, p_timezone)
  RETURNING * INTO v_business;

  -- THE DUPLICATE GUARD. On the auth account, not on users.id — the staff row's
  -- id is generated here and could never collide, so keying the guard on it
  -- after the retype would have meant no guard at all while still looking like
  -- one.
  --
  -- ON CONFLICT rather than a SELECT: `users` is under FORCE row-level security
  -- and an unscoped SELECT returns no rows for a user who definitely exists,
  -- so the guard would silently stop firing in the case it exists for. A unique
  -- index is not subject to visibility. DO NOTHING rather than DO UPDATE:
  -- updating is what 031's header describes as silently repointing an account
  -- at a newer tenant and stranding the previous one.
  INSERT INTO users (email, business_id, auth_uid)
  VALUES (p_email, v_id, p_auth_uid)
  ON CONFLICT DO NOTHING;

  IF NOT FOUND THEN
    -- Rolls back the business inserted moments ago, so a refused call leaves
    -- nothing behind. Covers BOTH unique indexes: the auth account already has
    -- a staff row, or the email address is already taken by another account.
    RAISE EXCEPTION 'app_create_business_for_user: this account or email already belongs to a business'
      USING ERRCODE = '23505';
  END IF;

  -- Hand the caller back the scope it arrived with. COALESCE because
  -- current_setting(..., true) returns NULL when unset and set_config wants a
  -- string; '' is what app_current_business_id() already treats as unset.
  PERFORM set_config('app.business_id', COALESCE(v_previous, ''), true);

  RETURN v_business;
END;
$$;

COMMENT ON FUNCTION app_create_business_for_user(text, text, text, text) IS
  'Bootstrap: creates a tenant and attaches the signing-up AUTH ACCOUNT to it. Takes the identity provider''s id as text — Identity Platform''s is not a uuid, and the previous uuid signature typechecked only because Supabase Auth happened to issue uuids. SECURITY DEFINER is not sufficient on its own because migration 029 uses FORCE ROW LEVEL SECURITY, so this generates the business id first and adopts it as the transaction-local tenant, making the insert satisfy the policy rather than bypass it. Restores the caller''s previous scope before returning.';

REVOKE ALL ON FUNCTION app_create_business_for_user(text, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_create_business_for_user(text, text, text, text) TO vetra_app;
