# ---------------------------------------------------------------------------
# The migration job.
#
# ---------------------------------------------------------------------------
# Why a Cloud Run Job and not a psql from a laptop
# ---------------------------------------------------------------------------
#
# The Cloud SQL instances are `ipv4_enabled = false`. There is no public
# endpoint, by design, so nothing outside the VPC can reach them — including
# this workstation, including the Cloud SQL Auth Proxy running on it.
#
# Something has to run INSIDE the VPC. A Cloud Run Job with Direct VPC egress is
# the smallest thing that does: it starts, connects over the private range,
# applies what is pending, and exits. It costs nothing when not running, which
# is almost always.
#
# It also rehearses the exact path D3 will use for the production restore, on a
# database where being wrong is free.
#
# ---------------------------------------------------------------------------
# The same image as the voice service
# ---------------------------------------------------------------------------
#
# One image, two entrypoints. The job overrides the command to
# `node scripts/migrate.js`; nothing else differs. A separate migration image
# would duplicate node_modules to carry ~200KB of SQL, and would be a second
# thing to remember to rebuild — which means a schema deploy running last
# week's migrations.
#
# TWO IDENTITIES, and the split is the point.
#
# The job runs AS the runtime service account (that is what Cloud Run needs to
# pull the image, reach the VPC and read one secret), but it CONNECTS to
# Postgres as the superuser. Applying a schema needs CREATE on `public`, role
# creation and ownership — privileges the runtime must never hold, because
# migration 029 makes `vetra_app` NOSUPERUSER NOBYPASSRLS precisely so the
# service cannot switch row-level security off.
#
# The first attempt ran the migrations as the IAM identity and failed with
# `permission denied for schema public`, which is the design working rather than
# a misconfiguration.
#
# So the job reads one Secret Manager secret, per-secret IAM, generated by
# Terraform and never seen by a human. Its last act is to GRANT `vetra_app` to
# the runtime principal, after which the service itself needs no password and no
# elevated rights.
# ---------------------------------------------------------------------------

variable "image_tag" {
  description = <<-EOT
    Tag of the voice image to run. Built by cloudbuild.yaml and pushed to the
    shared Artifact Registry.

    Default `latest` is right for the migration job specifically — a schema
    deploy should apply the newest migrations, and the job is idempotent, so
    re-running it is a no-op. It is NOT right for a Cloud Run service, where a
    floating tag makes a revision that cannot be reproduced; B4 pins a SHA.
  EOT
  type        = string
  default     = "latest"
}

# ---------------------------------------------------------------------------
# P2 — THE BUILD SHA. Cloud Run injects nothing; Railway injected it for free.
#
# `server.js` reports the running build on `GET /`:
#
#   const BUILD_SHA = process.env.RAILWAY_GIT_COMMIT_SHA
#                  || process.env.GIT_COMMIT_SHA || null;
#
# RAILWAY INJECTS THE FIRST AND CLOUD RUN INJECTS NEITHER, so after cutover
# every deployed service reports `Build: unknown` and "is my fix live?" goes
# back to being inferred from feature fingerprints. That inference has already
# been wrong once, and the recorded cost was a wasted test call spent against a
# revision running previous code — the same failure `dashboard_image_tag`'s own
# warning describes, arriving through a different door.
#
# So Terraform supplies it, on both services and on the migration job.
# ---------------------------------------------------------------------------
variable "git_commit_sha" {
  description = <<-EOT
    The commit the deployed images were built from, surfaced to the container as
    `GIT_COMMIT_SHA`.

    LEAVE IT EMPTY unless you have to. Empty means "use the image tag", and the
    documented build command substitutes `_TAG=$(git rev-parse --short HEAD)`,
    so the tag IS the commit under the normal workflow — and one value that
    cannot drift beats two that can.

    SET IT ONLY IF YOU TAG BY SOMETHING ELSE (`v1.4.2`, a build number). Then
    this is the commit and the tag is the release name.

    ⚠ IF YOU SET IT, IT IS NOW YOURS TO BUMP. A stale value here is worse than
    no value at all: `Build: unknown` sends someone to check, while a confident
    wrong SHA ends the investigation with the wrong answer. That is exactly the
    failure this variable exists to stop, pointed the other way.
  EOT
  type        = string
  default     = ""

  validation {
    condition     = var.git_commit_sha == "" || can(regex("^[0-9a-f]{7,40}$", var.git_commit_sha))
    error_message = "git_commit_sha must be 7-40 lowercase hex characters (a git SHA), or empty to fall back to the image tag."
  }
}

locals {
  voice_image = "${var.us_region}-docker.pkg.dev/${local.project_id_for_stack["shared"]}/${google_artifact_registry_repository.images.repository_id}/voice:${var.image_tag}"

  # One resolved value per image, because the two images have independent
  # lifecycles and therefore independent commits.
  voice_build_sha     = var.git_commit_sha != "" ? var.git_commit_sha : var.image_tag
  dashboard_build_sha = var.git_commit_sha != "" ? var.git_commit_sha : var.dashboard_image_tag

  # One migration job per database, because a job runs one `migrate.js` against
  # one connection. Merged staging with the UK toggle on would have two
  # databases on one instance and therefore two jobs.
  migrate_targets = merge([
    for ik, iv in local.active_sql_instances : {
      for db in iv.databases : "${ik}/${db.name}" => {
        instance_key = ik
        stack        = db.stack
        database     = db.name
        project_id   = iv.project_id
        region       = iv.region
      } if contains(keys(local.active_regional_stacks), db.stack)
    }
  ]...)
}

resource "google_cloud_run_v2_job" "migrate" {
  for_each = local.migrate_targets

  project  = each.value.project_id
  name     = "vetra-migrate-${each.value.stack}"
  location = each.value.region

  # Cloud Run refuses to create a job whose image cannot be pulled, so this is
  # also the check that the build actually pushed something.
  deletion_protection = false

  template {
    # A failed migration should be READ, not retried. The runner takes an
    # advisory lock and applies one transaction per file, so a retry is safe —
    # but it is also almost never the answer, and three identical failures in
    # the log make the real error harder to find.
    task_count  = 1
    parallelism = 1

    template {
      service_account = google_service_account.runtime[each.value.stack].email
      max_retries     = 0
      timeout         = "1800s"

      # -------------------------------------------------------------------
      # Direct VPC egress. C-6, and the reason this job can reach a private IP
      # at all.
      #
      # No Serverless VPC Access connector: those are real VM instances billed
      # per instance-hour whether or not a packet crosses them. This attaches
      # the job's own instance to the subnet, allocates one address from it for
      # the seconds the job runs, and costs nothing.
      #
      # PRIVATE_RANGES_ONLY, not ALL_TRAFFIC: the job needs the database and
      # Google's APIs, and nothing else. Its egress to the internet stays on
      # the default path rather than being routed through a VPC that has no NAT.
      # -------------------------------------------------------------------
      vpc_access {
        network_interfaces {
          network    = google_compute_network.this[each.value.instance_key].id
          subnetwork = google_compute_subnetwork.this[each.value.stack].id
        }
        egress = "PRIVATE_RANGES_ONLY"
      }

      containers {
        image   = local.voice_image
        command = ["node"]
        # --init-if-empty, not a bare migrate. A brand-new Cloud SQL database
        # has no tables, and the migrations are a forward sequence rather than a
        # from-zero install — running them against nothing fails at 002 with
        # `relation "businesses" does not exist`. The flag applies schema.sql as
        # the baseline when the database is empty and does nothing otherwise, so
        # the same job is correct today and at D3 after a restore.
        args = ["scripts/migrate.js", "--init-if-empty"]

        env {
          name  = "CLOUD_SQL_INSTANCE"
          value = google_sql_database_instance.this[each.value.instance_key].connection_name
        }

        # Migrations run as the SUPERUSER, not as the runtime identity. An IAM
        # user cannot create objects in `public` — the first attempt failed with
        # exactly `permission denied for schema public` — and giving the runtime
        # enough privilege to migrate would make migration 029's RLS decorative.
        env {
          name  = "CLOUD_SQL_IAM_USER"
          value = "postgres"
        }

        env {
          name = "CLOUD_SQL_PASSWORD"
          value_source {
            secret_key_ref {
              secret  = google_secret_manager_secret.postgres_password[each.value.instance_key].secret_id
              version = "latest"
            }
          }
        }

        # After the migrations that define `vetra_app`, hand its privileges to
        # the runtime principal by role MEMBERSHIP. The runtime then needs no
        # password and no elevated rights, and RLS still applies because it
        # inherits a role that is NOSUPERUSER NOBYPASSRLS.
        #
        # This cannot live in a migration file: it is a service account email
        # that differs per environment, and a migration is a fixed artefact with
        # a checksum over its contents.
        env {
          name  = "CLOUD_SQL_GRANT_APP_ROLE_TO"
          value = trimsuffix(google_service_account.runtime[each.value.stack].email, ".gserviceaccount.com")
        }

        env {
          name  = "CLOUD_SQL_DATABASE"
          value = each.value.database
        }

        resources {
          limits = {
            cpu    = "1"
            memory = "512Mi"
          }
        }
      }
    }
  }

  depends_on = [
    google_sql_user.runtime_iam,
    google_sql_user.postgres,
    google_project_iam_member.runtime,
    google_secret_manager_secret_iam_member.postgres_password_migrate,
  ]
}

output "migrate_jobs" {
  description = "Run with: gcloud run jobs execute <name> --region <region> --project <project> --wait"
  value = {
    for k, v in google_cloud_run_v2_job.migrate : k => {
      name    = v.name
      region  = v.location
      project = v.project
      image   = local.voice_image
    }
  }
}
