// ---------------------------------------------------------------------------
// Enforcing blindness on the TTS listening test.
//
// The listening pass is the one part of this work a machine cannot do, which
// makes it the part most vulnerable to the listener knowing which clip is
// which. Incumbent bias is real and it runs both ways: labelled as the current
// vendor a clip reads as "fine"; labelled as a challenger the same clip reads
// as "different". A blind pack is what makes the verdict worth acting on.
//
// Three properties do the work:
//   - filenames carry no vendor identity
//   - order is randomised WITHIN each sentence, and differs between sentences
//     (so one identified clip doesn't deanonymise the rest by position)
//   - sentences stay in script order, so the scorecard is followable
//
// Seeded, so a pack can be regenerated byte-identically — a blind test that
// can't be reproduced can't be re-checked.
// ---------------------------------------------------------------------------

/**
 * Deterministic PRNG (mulberry32). Seeded rather than Math.random so a pack is
 * reproducible from its seed alone.
 * @param {number} seed
 * @returns {function(): number} uniform in [0,1)
 */
function mulberry32(seed) {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * Fisher-Yates, using the supplied PRNG. Returns a new array.
 * @param {Array} arr
 * @param {function(): number} rand
 */
function shuffle(arr, rand) {
  const out = arr.slice();
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j], out[i]];
  }
  return out;
}

/**
 * Assemble a blind listening pack.
 *
 * @param {object} opts
 * @param {Array<{provider: string, line: string, mulaw: Buffer, ttfaMs?: number}>} opts.items
 * @param {number} [opts.seed=1]
 * @returns {{entries: Array<{filename: string, provider: string, line: string, mulaw: Buffer, ttfaMs?: number}>,
 *   answerKey: Record<string, string>, scorecard: string, seed: number}}
 */
export function buildBlindPack({ items = [], seed = 1 } = {}) {
  // Sentence groups keep their first-seen order: the listener needs to know
  // which scorecard row they are on, and that is not the thing being hidden.
  const lineOrder = [];
  const byLine = new Map();
  for (const item of items) {
    if (!byLine.has(item.line)) {
      byLine.set(item.line, []);
      lineOrder.push(item.line);
    }
    byLine.get(item.line).push(item);
  }

  const rand = mulberry32(seed);
  const entries = [];
  let position = 0;

  for (const line of lineOrder) {
    // Reshuffled per sentence, so vendor position is not a tell across the pack.
    for (const item of shuffle(byLine.get(line), rand)) {
      position += 1;
      // Zero-padded index first: filenames sort into playback order, so no
      // file browser or <Play> loop can silently reorder the test.
      const filename = `${String(position).padStart(2, "0")}-sample.wav`;
      entries.push({ ...item, filename, position });
    }
  }

  const answerKey = Object.fromEntries(entries.map((e) => [e.filename, e.provider]));

  const rows = entries
    .map((e) => `| ${e.filename} | ${e.line} |  |  |  |  |  |  |`)
    .join("\n");

  const scorecard = `# Blind TTS scorecard (seed ${seed})

Judge over a phone handset at 8kHz mu-law, not through monitors. Telephony
bandwidth erases most of what separates these models — if the scores come out
close, that is a real result, and an argument against paying top of range.

Score 1-5. Leave "notes" for anything you can only describe in words.

| file | sentence | natural | intelligible | names/numbers | pace | artifacts | notes |
|---|---|---|---|---|---|---|---|
${rows}

**Do not open answer-key.json until every row above is filled in.**
`;

  return { entries, answerKey, scorecard, seed };
}
